# --- General options --- #

theme: jekyll-theme-minimal
title: Gustavo's site
description: A compilation of my personal projects
logo: /assets/img/img_4029.jpg
show_downloads: false
google_analytics:

#kramdown:
#  math_engine: mathjax
comments: False

# To use Staticman comments, fill in repository, branch, and endpoint
staticman:
  repository : "aramisentreri/aramisentreri.github.io" # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL, but recommended for spam protection)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>
