# --- General options --- #

theme: jekyll-theme-minimal
title: Gustavo's site
description: A compilation of my personal projects
logo: /assets/img/img_4029.jpg

show_downloads: true
google_analytics:
